language: android
env:
  matrix:
    - ANDROID_TARGET=android-23  ANDROID_ABI=armeabi-v7a

android:
  components:
    - tools
    - build-tools-23.0.2
    - android-23
    - sys-img-armeabi-v7a-android-23
